### ISSUE TITLE
Timestamp in info file is hardcoded

### ISSUE THREAD

**Issue by brastak** [artipie/go-adapter#10]
https://github.com/artipie/go-adapter/blob/5817fba93eee67d31ca22d5e8d32dd14fd491f4b/src/main/java/com/artipie/goproxy/Goproxy.java#L216

Expected behavior: info file contains timestamp of an update action

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#10](https://github.com/artipie/go-adapter/issues/10) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6b6cc768-b849-4677-b765-9c541c472156); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
