### ISSUE TITLE
IT test requires installed go interpretator

### ISSUE THREAD

**Issue by brastak** [artipie/go-adapter#12]
Integration tests checks installed Go software on the build machine. It looks like redundant coupling. I consider the better solution is to generalize external dependencies for all adapters with Docker and test-containers. Then the only required external software will be a Docker, and test-containers will use appropriate image for test executions.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#12](https://github.com/artipie/go-adapter/issues/12) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1fa7cc72-5371-4f65-94d1-5b1d8df114fc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job
