### ISSUE TITLE
go-adapter build fails in tests after updating asto.

### ISSUE THREAD

**Issue by ChGen** [artipie/go-adapter#143]
`go-adapter` build fails in tests after updating asto.
Changes:

pom.xml:
```
-      <artifactId>asto</artifactId>
-      <version>v1.5.1</version>
+      <artifactId>asto-core</artifactId>
+      <version>v1.15.1</version>
```

Build command:
```
time mvn -X clean install -Pqulice
```

Logs are attached.
[go-adapter-new-asto.zip](https://github.com/artipie/go-adapter/files/10182533/go-adapter-new-asto.zip)

**Comment by olenagerasimova** [comment]
resolved
