### ISSUE TITLE
GoproxyITCase:savesAndLoads test should be splited

### ISSUE THREAD

**Issue by brastak** [artipie/go-adapter#18]
saveAndLoads methods checks 2 independent things:
- adapter allows upload several versions of artifact;
- go interpreter is able to work with generated metadata and uploaded binaries.

We can split this checks into 2 test methods for better visibility. These methods will not be independent, but execution order can be managed by Order annotation or w/ Nested classes (JUnit 5)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak can we close this?

**Comment by brastak** [comment]
@g4s8 no, this issue was created during PR review, it is not fixed now.

**Comment by 0crat** [comment]
The job [#18](https://github.com/artipie/go-adapter/issues/18) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/aeee5c62-d34a-4520-b881-e5d3383a2d97); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#18](https://github.com/artipie/go-adapter/issues/18), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#18](https://github.com/artipie/go-adapter/issues/18) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c4d725cd-a099-44eb-9804-78954b9a019a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
The job [#18](https://github.com/artipie/go-adapter/issues/18) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/eb11c22a-7187-44bc-8a2e-53b85798e218); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @brastak[/z](https://www.0crat.com/u/brastak) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by g4s8** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/go-adapter/issues/18#issuecomment-607717682))

@carlosmiranda The job [#18](https://github.com/artipie/go-adapter/issues/18) is assigned to @brastak[/z](https://www.0crat.com/u/brastak), you cannot resign, since you are not a `PO` or `ARC`
