### ISSUE TITLE
Code test coverage

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/go-adapter#26]
I think we need to set test code coverage, coverage reports and integrate with https://codecov.io/ as it is done in docker-adapter.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
@g4s8 could you assign me this issue please?

**Comment by 0crat** [comment]
The job [#26](https://github.com/artipie/go-adapter/issues/26) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9c88106c-2674-4c56-9a4a-114dc11f1b12); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#28](https://github.com/artipie/go-adapter/issues/28) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@g4s8 we need to make sure that problem reporter and problem solver are two different persons for next tasks, thanks!

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#129](https://github.com/artipie/go-adapter/issues/129) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#unknown]() is still not solved; solved: [#129](https://github.com/artipie/go-adapter/issues/129).
