### ISSUE TITLE
ZipSlice.java:35-38: Implement ZipSlice to get zip...

### ISSUE THREAD

**Issue by 0pdd** [artipie/go-adapter#34]
The puzzle `20-b2836b3a` from #20 has to be resolved: 

https://github.com/artipie/go-adapter/blob/26c8a935511e87573d9d85a5c0848c72312f6d03/src/main/java/com/artipie/http/ZipSlice.java#L35-L38

The puzzle was created by @g4s8 on 21-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@8362b1b91be7, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:artipie/maven-adapter#74" exists in estimates.xml, but the job is absent in the WBS among 53 jobs.
```

[0.53.9](https://github.com/zerocracy/farm): CID: [75e9b71a-bac8-4240-bf81-e9dc7a051e82](https://www.0crat.com/footprint/CT2E6TK9B/75e9b71a-bac8-4240-bf81-e9dc7a051e82), Type: "Request order start"

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/go-adapter/issues/34#issuecomment-616965510))

@g4s8 This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#34](https://github.com/artipie/go-adapter/issues/34) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fgo-adapter%2334%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `20-b2836b3a` has disappeared from the source code, that's why I closed this issue.

**Comment by olenagerasimova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/go-adapter/issues/34#issuecomment-617584175))

@olenagerasimova This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#34](https://github.com/artipie/go-adapter/issues/34) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fgo-adapter%2334%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by olenagerasimova** [comment]
@g4s8 can I get my reputation point for this job, please?

**Comment by g4s8** [comment]
@0crat assign @olenagerasimova

**Comment by 0crat** [comment]
> @0crat assign @olenagerasimova  ([here](https://github.com/artipie/go-adapter/issues/34#issuecomment-618289100))

@g4s8 Job [#34](https://github.com/artipie/go-adapter/issues/34) is closed, can't start order
