### ISSUE TITLE
InfoSlice.java:35-38: Implement InfoSlice to get info...

### ISSUE THREAD

**Issue by 0pdd** [artipie/go-adapter#35]
The puzzle `20-41bda94c` from #20 has to be resolved: 

https://github.com/artipie/go-adapter/blob/26c8a935511e87573d9d85a5c0848c72312f6d03/src/main/java/com/artipie/http/InfoSlice.java#L35-L38

The puzzle was created by @g4s8 on 21-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `20-41bda94c` has disappeared from the source code, that's why I closed this issue.
