### ISSUE TITLE
LatestSlice.java:49-50: Make `latest` replacement in...

### ISSUE THREAD

**Issue by 0pdd** [artipie/go-adapter#39]
The puzzle `33-5bb0e272` from #33 has to be resolved: 

https://github.com/artipie/go-adapter/blob/b43f64e4d8ec7a223549a0b42d334c7fec962733/src/main/java/com/artipie/http/LatestSlice.java#L49-L50

The puzzle was created by olenagerasimova on 23-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#39](https://github.com/artipie/go-adapter/issues/39) assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5a1b378b-2b32-4d6c-ab71-00927e1f4183); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `33-5bb0e272` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @hdouss[/z](https://www.0crat.com/u/hdouss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@olenagerasimova there is test failure:
```
[1;34mINFOm] Running com.artipie.http.GoSliceITCase
[0;31mERRORm] main org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy: ping failed with configuration Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock due to org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.3`
