### ISSUE TITLE
Don't upload codecov for matrix build

### ISSUE THREAD

**Issue by g4s8** [artipie/go-adapter#44]
Code coverages are uploaded 6 times on each build from matrix OS/JDK: [windows,ubuntu][1.8,11,13]. Let's upload it only once. See #43

**Comment by 0crat** [comment]
The job [#44](https://github.com/artipie/go-adapter/issues/44) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/00d95b6a-32a9-48eb-8bed-9bfa7bc62382); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 8 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
