### ISSUE TITLE
Migrate to asto 0.11

### ISSUE THREAD

**Issue by Sammers21** [artipie/go-adapter#6]
Go adapter should be updated to the latest version of asto.

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/go-adapter/issues/6#issuecomment-588152988))

@g4s8 The job [#6](https://github.com/artipie/go-adapter/issues/6) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6935e907-7ca6-49a2-b43b-73e5df1767a6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@Sammers21 it's outdated

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/go-adapter/issues/6#issuecomment-598081698))

@g4s8 Job `gh:artipie/go-adapter#6` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:artipie/go-adapter#6` is not assigned, can't get performer
