### ISSUE TITLE
Add basic authorization support

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/go-adapter#62]
Let's add authorization support to go-adapter.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#66](https://github.com/artipie/go-adapter/issues/66) is still not solved.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4`

**Comment by olenagerasimova** [comment]
@yegor256 could you please help me with release here by fixing `.rultor.yml`?

**Comment by olegmoz** [comment]
@rultor release, tag=`0.4`

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#130](https://github.com/artipie/go-adapter/issues/130) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#unknown]() is still not solved; solved: [#130](https://github.com/artipie/go-adapter/issues/130).
