### ISSUE TITLE
License header changes

### ISSUE THREAD

**Issue by Sammers21** [artipie/go-adapter#7]
`Yegor B.` should be replaced with `artipie.com`

**Comment by 0crat** [comment]
The job [#7](https://github.com/artipie/go-adapter/issues/7) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3773e3e3-ba6e-4325-9d2c-708b7ce6275a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@Sammers21 @g4s8 see PR #21 please.

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
